### PR TITLE
Do not report error when no child process can be wait()-ed

### PR DESCRIPTION
**Pull request by d3m3t3r**
Do not treat wait() returning -1 and ECHILD as an error.

### CODE REVIEW

**Comment by i-ky** [comment]
What are you trying to achieve?

I guess you are trying to either get rid of the `cannot wait(): No child processes` error or the `-1` exit code at the end of successful execution.

I am not saying that always returning `-1` and printing an error message is the best solution, but always returning `0` (like `basset` does with your changes) may not be the best as well. Maybe we need something completely different...

One possible option is to mimic `strace`:
> When _command_ exits, `strace` exits with the same exit status.  If
       command is terminated by a signal, `strace` terminates itself with
       the same signal, so that strace can be used as a wrapper process
       transparent to the invoking parent process.

What are your thoughts?

**Comment by i-ky** [comment]
@d3m3t3r, sorry, but I'm struggling to "decrypt" the diff of your changes. Could you please walk me through what you have done there?

**Comment by d3m3t3r** [comment]
I made basset to return the same exit code as returned by the build command (==`main_pid`).  For that I had to "switch/rearrange" parent and child processes after fork().

**Comment by i-ky** [comment]
Hi @d3m3t3r!

I am terribly sorry for a delayed response, I had quite a lot happening offline lately.

> For that I had to "switch/rearrange" parent and child processes after fork().

I don't understand the reason to do it. I decided to give it a try myself and seemingly succeeded with a much neater diff. Could you please try #5 out and let me know if it behaves as you want it to?

**Comment by d3m3t3r** [comment]
#5 is fine.   
My re-arrangement is not necessary, I just find the current layout a bit unusual:
```
...parent
if ( fork() ) {
    ...parent with long logic
   return
}
...child with simple execve()
return
```

**Comment by i-ky** [comment]
> #5 is fine.

Thank you for reviewing! I will merge #5 then and close this one.

**Comment by i-ky** [comment]
> I just find the current layout a bit unusual:
> 
> ```
> ...parent
> if ( fork() ) {
>     ...parent with long logic
>    return
> }
> ...child with simple execve()
> return
> ```

It just happened this way... Feel free to file a PR. I am open to refactoring suggestions, I just don't like them mixed with features/bugfixes.

**Pull request closed without merging**
